[package]
name = "mem-common"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "mem_debug_cli"
path = "src/mem_debug_cli.rs"

[dependencies]
zisk-core = { workspace = true }
zisk-common = { workspace = true }
zisk-pil = { workspace = true }

proofman-common = { workspace = true }
proofman-macros = { workspace = true }
proofman = { workspace = true }
proofman-util = { workspace = true }
witness = { workspace = true }
pil-std-lib = { workspace = true }
fields = { workspace=true }
tracing = { workspace = true }
rayon = { workspace = true }
num-bigint = { workspace = true }
clap = { version = "4", features = ["derive"] }

num-traits = "0.2"

[features]
default = []
no_lib_link = ["proofman-common/no_lib_link"]
diagnostic = ["proofman-macros/diagnostic"]
disable_distributed = ["proofman/disable_distributed", "proofman-common/disable_distributed"]
debug_mem = []
debug_mem_align = []
save_mem_bus_data = []
mem_align_stats = []
