[package]
name = "distributed-prover-service"
description = "Command-line client for Distributed Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "distributed_client"
path = "src/lib.rs"

[[bin]]
name = "distributed-client"
path = "bin/main.rs"

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "git2",
] }

[dependencies]
cargo-zisk = { workspace = true }
zisk-common = { workspace = true }
proofman = { workspace = true }
proofman-common = { workspace = true }
rom-setup = { workspace = true }
asm-runner = { workspace = true }
distributed-grpc-api = { workspace = true }
distributed-coordinator = { workspace = true }
distributed-prover = { workspace = true }
distributed-common = { workspace = true }

tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
prost-types = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
colored = { workspace = true }
toml = { workspace = true }
