[package]
name = "zisk-distributed-common"
version = "0.1.0"
edition = "2021"

[dependencies]
proofman = { workspace = true }
proofman-common = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
borsh = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
thiserror = "2.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
