[worker]
# worker_id = "my-worker-001"
compute_capacity.compute_units = 10
environment = "production"

[coordinator]
url = "http://127.0.0.1:50051"

[connection]
reconnect_interval_seconds = 5
heartbeat_timeout_seconds = 30

[logging]
level = "info"
format = "pretty"
file_path = "/var/log/distributed/worker.log"