[package]
name = "distributed-comm"
description = "Peer-to-peer communication layer for Distributed Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
distributed-config = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
