[package]
name = "distributed-coordinator-cli"
description = "Main server binary for Distributed Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "coordinator"
path = "src/main.rs"

[dependencies]
distributed-coordinator = { workspace = true }
distributed-grpc-api = { workspace = true }
distributed-config = { workspace = true }
distributed-common = { workspace = true }
witness = { workspace = true }

tonic = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
