name: Riscof Tests

on:
  pull_request:
    branches:
      - develop
      - main
      - "pre-develop-[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "emulator/**"
      - "riscv/**"
      - "core/**"
      - "lib-float/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  riscof-elf-tests-rust:
    name: Riscof ELF tests (rust emulator)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
    env:
      ZISK_GHA: "1"
      ZISK_REPO_DIR: ${{ github.workspace }}
      TERM: xterm
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout zisk-testvectors repo
        uses: actions/checkout@v4
        with:
          repository: 0xPolygonHermez/zisk-testvectors
          path: zisk-testvectors
          ref: feature/imacfd

      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          sudo ./install_deps.sh

      - name: Emulate in rust Riscof ELF files
        run: |
          . "$HOME/.cargo/env"
          cd "$GITHUB_WORKSPACE"
          sudo ./tools/emulate_all.sh $GITHUB_WORKSPACE/zisk-testvectors/riscof/riscof_work

  riscof-elf-tests-asm:
    name: Riscof ELF tests (assembly emulator)
    runs-on: ubuntu-latest
    timeout-minutes: 200
    defaults:
      run:
        shell: bash
    env:
      ZISK_GHA: "1"
      ZISK_REPO_DIR: ${{ github.workspace }}
      TERM: xterm
    steps:
      - name: Increase shared memory (/dev/shm)
        run: |
          set -euxo pipefail
          df -h /dev/shm || true
          sudo mount -o remount,size=16G /dev/shm || sudo mount -o remount,size=16G /run/shm
          df -h /dev/shm

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout zisk-testvectors repo
        uses: actions/checkout@v4
        with:
          repository: 0xPolygonHermez/zisk-testvectors
          path: zisk-testvectors
          ref: feature/imacfd

      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          sudo ./install_deps.sh

      - name: Emulate in assembly Riscof ELF files
        run: |
          . "$HOME/.cargo/env"
          cd "$GITHUB_WORKSPACE"
          sudo ./tools/emulate_asm_all.sh $GITHUB_WORKSPACE/zisk-testvectors/riscof/riscof_work